[package]
edition = "2024"
name = "project06_nunchuk_driver_demo"
version = "0.1.0"
license = "MIT OR Apache-2.0"

[dependencies]
# defmt
defmt = { workspace = true }
defmt-rtt = { workspace = true }
panic-probe = { workspace = true }

# embassy
embassy-time = { workspace = true }
embassy-executor = { workspace = true }
embassy-sync = { workspace = true }
embassy-embedded-hal = { workspace = true }
embassy-futures = { workspace = true }

#stm32f3 (platform)
embassy-stm32 = { workspace = true }
cortex-m = { workspace = true }
cortex-m-rt = { workspace = true }

# Driver library (common utils)
embedded-core = { workspace = true }

# Others
static_cell = { workspace = true }

# embedded graphics
embedded-graphics = { workspace = true }
