[package]
edition = "2024"
name = "project00_hello_world"
rust-version = "1.88"
version = "0.1.0"


[dependencies]
esp-hal = { workspace = true }
esp-rtos = { workspace = true }
esp-bootloader-esp-idf = { workspace = true }
embassy-executor = { workspace = true }
embassy-time = { workspace = true }
esp-alloc = { workspace = true }
rtt-target = { workspace = true }
