[package]
edition = "2024"
name = "project00_hello_world"
rust-version = "1.88"
version = "0.1.0"


[dependencies]
# defmt
defmt = { workspace = true }
esp-println = { workspace = true }
esp-backtrace = { workspace = true }

# embassy
embassy-executor = { workspace = true }
embassy-time = { workspace = true }

# esp
esp-hal = { workspace = true }
esp-rtos = { workspace = true }
esp-bootloader-esp-idf = { workspace = true }
esp-alloc = { workspace = true }
