[package]
name = "common-utils"
version = "0.1.0"
edition = "2021"
rust-version = "1.83"

[features]
# default build is no_std
default = []

# enable std explicitly (e.g. during cargo test)
std = []

[dependencies]
heapless = { workspace = true }
defmt = { workspace = true }
embassy-nrf = { workspace = true }
async-trait = { workspace = true }
embassy-time = { workspace = true }


# conditional dependencies for "std" (used in tests or PC)
# [dependencies.embedded-hal]
# version = "1.0.0-alpha.10"
# optional = true

# dev dependencies for testing with mocks
[dev-dependencies]
embedded-hal = "1.0.0-alpha.10"
embedded-hal-mock = { version = "0.10", features = ["eh0"] }
# async-trait = { version = "0.1" }
