[package]
name = "common-utils"
version = "0.1.0"
edition = "2021"
rust-version = "1.83"

[features]
# default build is no_std
default = []

# enable std explicitly (e.g. during cargo test)
std = []

[dependencies]
heapless = { workspace = true }
defmt = { workspace = true }
embassy-nrf = { workspace = true }
async-trait = { workspace = true }
embassy-time = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
embedded-hal = { workspace = true }
embedded-hal-mock = { workspace = true }
